Repository Dishika18/InsightSync, pull requests merged in 2025-02, with the labels that each got.

#177 Added sorting by topics
  js/signup.js
  server/controller/insight.controller.js
  topics-listing.html
Labels: SWOC, INTERMEDIATE, Points Pending

#166 Fixed Login/Signup Buttons in Mobile View
  add-topics.html
  contact.html
  css/style.css
  feedbackform.html
  index.html
  topics-detail.html
  topics-listing.html
Labels: SWOC, INTERMEDIATE, Points Pending

#178 add random topics on index page
  IndexPage.js
  index.html
Labels: SWOC, Points Pending

#181 added backend setup instruction
  README.md
  server/.env.sample
  server/deplyment.md
Labels: SWOC, BEGINNER

#185 Created `LICENSE`
  LICENSE
Labels: SWOC, BEGINNER

#182 added like functionaly backend
  server/controller/insight.controller.js
  server/models/User.js
  server/models/insight.model.js
  server/routes/insight.route.js
Labels: SWOC, ADVANCE

#186 Fixed the issue of not being able to Login & Signup from Contact Page
  contact.html
Labels: SWOC, INTERMEDIATE

#189 Fixed Testimonial Images
  testimonial.css
Labels: SWOC, BEGINNER

#190 added liked functionality
  js/login.js
  server/controller/authController.js
  topics-detail.html
Labels: SWOC, INTERMEDIATE

#196 added markdown support
  add-topics.html
Labels: SWOC, INTERMEDIATE

#200 Update style.css
  css/style.css
Labels: SWOC, BEGINNER, Points Pending

#188 Update testimonial.css
  testimonial.css
Labels: SWOC

#202 Add links to the feedback form
  feedbackform.html
Labels: SWOC, BEGINNER, Points Pending

#207 Feature/topic list enhancement
  .vscode/settings.json
  topics-listing.html
Labels: SWOC, INTERMEDIATE, Points Pending

#209 added savefor later fronend
  profile.html
  topics-detail.html
Labels: SWOC, INTERMEDIATE, Points Pending

#215 Added links in navbar of topics-detail.html
  topics-detail.html
Labels: SWOC, BEGINNER, Points Pending

#219 footer ui improve
  css/style.css
  index.html
Labels: SWOC, BEGINNER, Points Pending

#218 i have added the public profile controllers
  server/controller/insight.controller.js
  server/controller/profile.controller.js
  server/routes/profile.routes.js
  topics-detail.html
Labels: SWOC, INTERMEDIATE

#226 Add Animated Scroll-to-Top Button Across All Pages.
  add-topics.html
  contact.html
  css/Scroll.css
  feedbackform.html
  index.html
  js/click-scroll.js
  topics-listing.html
Labels: SWOC, INTERMEDIATE, Points Pending

#228 Implement comment functionality with add, get, and delete operations
  server/api/app.js
  server/controller/comment.controller.js
  server/models/User.js
  server/models/comment.model.js
  server/models/insight.model.js
  server/routes/comment.router.js
Labels: SWOC, ADVANCE

#229 Add functionality to fetch comments by insight ID and update comment handling
  addcomment.js
  fetchcomment.js
  server/controller/comment.controller.js
  server/routes/comment.router.js
  topics-detail.html
Labels: SWOC, ADVANCE
