Repository Dishika18/InsightSync, pull requests merged in 2025-01, with the labels that each got.

#12 subscribe to newsletter feature added
  css/style.css
  index.html
Labels: SWOC, BEGINNER

#13 Added Login Page With Responsive UI
  contact.html
  css/style.css
  index.html
  topics-detail.html
  topics-listing.html
Labels: SWOC, BEGINNER

#21 Added insights backend
  .gitignore
  index.html
  indexhtmlbackup.txt
  package-lock.json
  package.json
  server/.gitignore
  server/api/.env.sample
  server/api/app.js
  server/api/dbconnect.js
  server/api/index.js
  server/controller/insight.controller.js
  server/models/insight.model.js
  server/package-lock.json
  server/package.json
  server/routes/insight.route.js
  server/utils/cloudinary.utils.js
  server/vercel.json
  topics-detail.html
  topics-listing.html
  trending topics_and_footer.txt
Labels: SWOC, ADVANCE

#33 Added page to add topic details
  add-topics.html
  contact.html
  index.html
  topics-detail.html
  topics-listing.html
Labels: SWOC, INTERMEDIATE

#40 Testimonials added on navbar of contact.html,add-topics.html,topics-d…
  add-topics.html
  contact.html
  topics-detail.html
  topics-listing.html
Labels: SWOC, BEGINNER

#46 Fixes based on feedback (Testimonials Misaligned Images)
  index.html
  testimonial.css
Labels: SWOC, BEGINNER

#48 updated copyright containing tag and bought it to the very bottom
  add-topics.html
  contact.html
  css/style.css
  index.html
  topics-detail.html
  topics-listing.html
Labels: SWOC, BEGINNER

#56 added placeholder in add-topics.html
  add-topics.html
Labels: SWOC, BEGINNER

#58 adding favicon #6
  images/favicon.png
  index.html
Labels: SWOC, BEGINNER

#57 adding_socialmedia_links
  contact.html
  css/style.css
  index.html
  topics-detail.html
  topics-listing.html
Labels: SWOC, BEGINNER

#61 Increase width of menu
  css/style.css
Labels: SWOC, BEGINNER

#62 content on the index.html is ready #1
  index.html
Labels: SWOC, BEGINNER

#70 Added Responsive footer to add-topics.html
  add-topics.html
Labels: SWOC, BEGINNER

#85 Changed the styles of Topics-listing page and added profile
  Baselink.js
  add-topics.html
  index.html
  js/login.js
  js/signup.js
  profile.html
  server/api/app.js
  server/controller/authController.js
  server/controller/insight.controller.js
  server/controller/profile.controller.js
  server/models/User.js
  server/models/insight.model.js
  server/routes/insight.route.js
  server/routes/profile.routes.js
  topics-detail.html
  topics-listing.html
Labels: SWOC, ADVANCE

#87 Add Testimonials & Browse Topics in Footer of CONTACT PAGE
  contact.html
Labels: SWOC, BEGINNER

#89 In finanace card the social media icons earlier overlaped with the ca…
  css/style.css
  index.html
Labels: SWOC, BEGINNER

#100 Added testimonials and browse topics to add-topics.html page
  add-topics.html
  contact.html
Labels: SWOC, BEGINNER

#101 Added a dynamically updating contributors list in README.md
  README.md
Labels: SWOC, BEGINNER

#102 "login prompt for non-logged in users added in add-topics page"
  add-topics.html
Labels: SWOC, INTERMEDIATE

#105 accordian is now fixed, closed by default
  index.html
Labels: SWOC, BEGINNER

#109 Missing Testimonials & Browse Topics in Footer (TOPICS DETAIL PAGE)
  topics-detail.html
Labels: SWOC, BEGINNER

#113 Integrate AI Chatbot for Enhanced User Guidance and Support
  css/style.css
  index.html
Labels: SWOC, ADVANCE

#103 Bug in contactPage and profile pages (and topics listing page style)
  contact.html
  profile.html
Labels: SWOC, ADVANCE

#114 Added Links of different sections of Home Page in topics-detail.html in Navbar
  topics-detail.html
Labels: SWOC, BEGINNER

#115 Add Links of different sections of Home Page in topics-listing.html of NAVBAR
  topics-listing.html
Labels: SWOC, BEGINNER

#116 Fixed login & signup in add-topics page
  add-topics.html
Labels: SWOC, INTERMEDIATE

#117 Error 404 page added
  404.html
  images/robot-state-3.png
  server/api/app.js
Labels: SWOC, ADVANCE

#136 Added more profile controllers
  server/controller/profile.controller.js
  server/models/User.js
  server/routes/profile.routes.js
Labels: SWOC, INTERMEDIATE, Points Pending

#139 fix: fix submit color in add-topic.html
  css/style.css
Labels: SWOC, BEGINNER

#142 adding files for database connection for contact file
  contact.html
  js/contacts.js
  server/api/.env.sample
  server/api/app.js
  server/api/dbconnect.js
  server/models/contact.js
  server/routes/contact.route.js
Labels: SWOC, INTERMEDIATE, Points Pending

#147 Added edit profile section
  edit-profile.html
  profile.html
  server/controller/insight.controller.js
  server/routes/insight.route.js
Labels: SWOC, INTERMEDIATE, Points Pending

#148 Add feedback form
  add-topics.html
  contact.html
  feedbackform.css
  feedbackform.html
  feedbackform.js
  index.html
  topics-detail.html
  topics-listing.html
Labels: SWOC, INTERMEDIATE, Points Pending

#150 Change Login & Signup Text to Static and removed the Emoji
  index.html
Labels: SWOC, BEGINNER

#154 I have added controllers for editing and deleting insights
  .gitignore
  server/controller/insight.controller.js
  server/controller/profile.controller.js
  server/routes/insight.route.js
  vercelbackup.txt
Labels: SWOC, ADVANCE, Points Pending

#153 redesigned search box
  css/style.css
  topics-listing.html
Labels: SWOC, BEGINNER

#156 added edit insight frontend page
  edit-insight.html
  topics-detail.html
Labels: SWOC, INTERMEDIATE, Points Pending

#160 #157-notifications styled
  add-topics.html
  contact.html
  css/style.css
  edit-profile.html
  index.html
  js/contacts.js
  js/login.js
  js/signup.js
  profile.html
Labels: SWOC, ADVANCE, Points Pending

#162 🚀 Enhanced Login Page with Placeholder Text 📝
  index.html
Labels: SWOC, BEGINNER, Points Pending

#169 Added dynamic year change feature on all pages
  add-topics.html
  contact.html
  feedbackform.html
  index.html
  topics-detail.html
  topics-listing.html
Labels: SWOC, BEGINNER, Points Pending
