Repository Dishika18/InsightSync, pull requests merged in 2025-03, with the labels that each got.

#230 fixed the copyright on the home page
  index.html
Labels: SWOC, BEGINNER

#231 Added Sorting by Likes
  topics-listing.html
Labels: SWOC, INTERMEDIATE, Points Pending

#232 Update public profile route and link in topics detail page
  puplicprofile.html
  server/controller/profile.controller.js
  server/routes/profile.routes.js
  topics-detail.html
Labels: SWOC, ADVANCE, Points Pending

#237 Added pr and issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: apertre2.0, Doc

#238 made navbar working in contact section
  contact.html
Labels: apertre2.0, Easy

#246 Bug/show success message on newsletter subscription instead of http error 405
  index.html
Labels: apertre2.0, Medium

#249 [FEATURE]: Implement Search Functionality for Topics
  IndexPage.js
  index.html
Labels: apertre2.0, Medium

#252 UI redesign for profile.html #211
  profile.html
Labels: apertre2.0, Medium

#254 Added AI summarization feature
  summary.js
  topics-detail.html
Labels: apertre2.0, Hard
